DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS recipes CASCADE;
DROP TABLE IF EXISTS wines CASCADE;
DROP TABLE IF EXISTS desserts CASCADE;


CREATE TABLE threads (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT,
  flair TEXT,
  upvotes INT,
  downvotes INT,
  image TEXT
);

CREATE TABLE responses (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  q_and_a JSONB[],
  thread_id BIGINT NOT NULL REFERENCES threads(id)
);

CREATE TABLE recipes (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  recipe JSON NOT NULL
);

CREATE TABLE wines (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  wine JSON NOT NULL
);

CREATE TABLE desserts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  dessert JSON NOT NULL
);
