DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS responses CASCADE;

CREATE TABLE threads (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  author TEXT NOT NULL,
  flair TEXT,
  upvotes INT,
  downvotes INT,
  image TEXT
);

CREATE TABLE responses (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  q_and_a JSONB,
  thread_id BIGINT NOT NULL REFERENCES threads(id)
);
